[versions]
agp = "8.11.2"
gson = "2.13.2"
appcompat = "1.7.1"
material = "1.13.0"
workRuntime = "2.11.0"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

